### PR TITLE
Changed the font-weight to Table Headers

### PR DESCRIPTION
**Pull request by benmak11**
On windows machines the font is too heavy that it is hard to decipher an "i" from an "l".

image

### CODE REVIEW

**Comment by mdwragg** [comment]
Hi, we can't accept the change like this sadly - changing the design of the component just isn't possible without review from our designers.

A workaround would be to expose the font weight via a CSS variable (see here for more info https://www.polymer-project.org/1.0/docs/devguide/styling).

Also, the HTML style modules are compiled from the SCSS files in the `sass/` folder - please make your changes to the sass and recompile the html modules using `gulp sass`.

Thanks!

**Comment by mdwragg** [comment]
@PredixDev/px - Please do not merge this.

**Comment by benmak11** [comment]
@mdwragg Who do we need to talk to so I can get the approval on this UX change?

**Comment by mdwragg** [comment]
@benmak11, I would encourage you to create a PR that exposes the font weight as a CSS variable, thus we can maintain our design and you have control over the weight for your need.

**Comment by benmak11** [comment]
Okay thank you @mdwragg!

**Pull request closed without merging**
