### PR TITLE
When hide-pagination-control is true, all items will be displayed (instead of only the first page)

### PR DESCRIPTION
**Pull request by justinsrd**
I'm part of the APM Alerts team. You added the hidePaginationControl option, but it only hid the pagination controls. It still displayed the first 10 items in the dataset.

### CODE REVIEW

**Comment by carlosfhernandez** [comment]
It is possible you have worked off an old version of master. Please check, merge master back into your fork, and we will take a look. A test is failing (Sauce) indicating this could be the case.

**Comment by carlosfhernandez** [comment]
Will look at this and evaluate for next sprint.

**Comment by mdwragg** [comment]
Hi @justinsrd - thanks for the PR! do you mind merging in the master changes to your PR? Also, could you provide some unit tests (see the existing tests for examples and build your own test fixture & suite).

I've fixed up travis so that your fork should be able to run tests in travis CI now, once you merge in the head of master it should start working.

Thanks!

**Comment by mdwragg** [comment]
@justinsrd - waiting for your update, we're happy to accept it see ^^

**Comment by justinsrd** [comment]
@mdwragg Hi! Sorry, I've been out sick the past couple of days. I'll get right on it!

**Comment by mdwragg** [comment]
Glad you're back and healthy! Thanks :-)

**Comment by benoitjchevalier** [comment]
Hi @justinsrd , could you merge the master branch again please? There's a conflict which prevents the tests from running at the moment

**Pull request closed without merging**
